services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /tf
    volumes:
      - ./src:/tf
      - ./data/PolyMNIST/MMNIST/test/m0:/tf/data/test
      - ./data/PolyMNIST/MMNIST/train/m0:/tf/data/train
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
